tabItem(
  tabName = "drug",
  fluidRow(
    column(9,
           bsAlert("drugmess"),
           bsCollapse(id = "collapsedrug", open = "Descriptions and parameters",
                      bsCollapsePanel("Descriptions and parameters",  includeHTML("drug.html"), style = "default"),
                      bsCollapsePanel("Correlation with drug response",style = "default",
                                      tabBox(width = NULL,
                                             tabPanel("Drug response plot", align="center",
                                                      uiOutput('drugplot',align = "center"),
                                                      useShinyjs(),
                                                      fluidRow(column(4,align="left",
                                                                      hidden(div(id = "drugplot_wrapper",
                                                                                 splitLayout(
                                                                                   numericInput("drugpltwidth","Figure width",value = 10),
                                                                                   numericInput("drugpltheight","Figure height",value = 10)),
                                                                                 downloadButton('savedrugness', 'Download figure', class = "butt2")
                                                                      ))
                                                      ))
                                             ),
                                             tabPanel("Drug response table", DT::dataTableOutput('drugtable'),align="center",
                                                      useShinyjs(),
                                                      fluidRow(column(4,
                                                                      hidden(div(id = "drugtable_wrapper",
                                                                                 downloadButton('savedrugtable', 'Download table', class = "butt2")
                                                                      ))
                                                      ))
                                             )
                                      )
                      ))
    ),
    column(3,box(
      title = "Correlation with drug response",
      width = NULL,
      status = "danger",
      solidHeader = T,
      collapsible = T,
      collapsed = F,
      
      selectizeInput(
        "druggene",
        label = "Official gene symbol",
        choices = NULL,
        multiple = F
      ),
      bsTooltip("druggene", "Input one gene (biomarker candidate) with official gene symbol that you want to analyze the correlation between the gene and the drug response.","left"),
      
      selectizeInput(
        "drugs",
        label = "Drug",
        choices =  c(
          "Erlotinib"    ,
          "Rapamycin"        ,
          "Sunitinib"     ,
          "PHA-665752"     ,
          "MG-132"    ,
          "Paclitaxel"      ,
          "Cyclopamine" ,
          "AZ628"            ,
          "Sorafenib"       ,
          "VX-680"         ,
          "Imatinib"   ,
          "TAE684"      ,
          "Crizotinib" ,
          "Saracatinib"     ,
          "S-Trityl-L-cysteine",
          "Z-LLNle-CHO"    ,
          "Dasatinib"  ,
          "GNF-2"      ,
          "CGP-60474"  ,
          "CGP-082996"      ,
          "A-770041"   ,
          "WH-4-023"       ,
          "WZ-1-84"     ,
          "BI-2536"      ,
          "BMS-536924"  ,
          "BMS-509744"       ,
          "CMK"           ,
          "Pyrimethamine"  ,
          "JW-7-52-1"  ,
          "A-443654"      ,
          "GW843682X"  ,
          "MS-275"            ,
          "Parthenolide"    ,
          "KIN001-135"     ,
          "TGX221"     ,
          "Bortezomib"      ,
          "XMD8-85"     ,
          "Roscovitine"      ,
          "Salubrinal"    ,
          "Lapatinib"     ,
          "GSK269962A" ,
          "Doxorubicin"      ,
          "Etoposide"  ,
          "Gemcitabine"     ,
          "Mitomycin C"     ,
          "Vinorelbine"   ,
          "NSC-87877"    ,
          "Bicalutamide"      ,
          "QS11"      ,
          "CP466722"       ,
          "Midostaurin"    ,
          "CHIR-99021"    ,
          "AP-24534"    ,
          "AZD6482"      ,
          "JNK-9L"    ,
          "PF-562271"       ,
          "HG-6-64-1"      ,
          "JQ1"           ,
          "JQ12"       ,
          "DMOG"      ,
          "FTI-277"    ,
          "OSU-03012"       ,
          "Shikonin"       ,
          "AKT inhibitor VIII",
          "Embelin"    ,
          "FH535"      ,
          "PAC-1"    ,
          "IPA-3"            ,
          "GSK-650394"    ,
          "BAY 61-3606"     ,
          "5-Fluorouracil" ,
          "Thapsigargin"      ,
          "Obatoclax Mesylate" ,
          "BMS-754807"       ,
          "Lisitinib"    ,
          "Bexarotene"     ,
          "Bleomycin"    ,
          "LFM-A13"      ,
          "GW-2580"       ,
          "AUY922"           ,
          "Phenformin"   ,
          "Bryostatin 1"   ,
          "Pazopanib"   ,
          "LAQ824"      ,
          "Epothilone B"   ,
          "GSK1904529A"       ,
          "BMS345541"  ,
          "Tipifarnib"      ,
          "BMS-708163"    ,
          "Ruxolitinib" ,
          "AS601245"   ,
          "Ispinesib Mesylate" ,
          "TL-2-105"  ,
          "AT-7519"        ,
          "TAK-715"      ,
          "BX-912"  ,
          "ZSTK474"    ,
          "AS605240"         ,
          "Genentech Cpd 10" ,
          "GSK1070916"     ,
          "KIN001-102"   ,
          "LY317615"      ,
          "GSK429286A"   ,
          "FMK"           ,
          "QL-XII-47"   ,
          "CAL-101"       ,
          "UNC0638"      ,
          "XL-184"      ,
          "WZ3105"    ,
          "XMD14-99"      ,
          "AC220"     ,
          "CP724714"       ,
          "JW-7-24-1"    ,
          "NPK76-II-72-1"      ,
          "STF-62247"     ,
          "NG-25"          ,
          "TL-1-85"     ,
          "VX-11e"        ,
          "FR-180204"     ,
          "Tubastatin A"      ,
          "Zibotentan"   ,
          "YM155"          ,
          "NSC-207895"    ,
          "VNLG/124"       ,
          "AR-42"        ,
          "CUDC-101"      ,
          "Belinostat"   ,
          "I-BET-762"     ,
          "CAY10603"   ,
          "Linifanib "    ,
          "BIX02189"     ,
          "CH5424802"      ,
          "EKB-569"   ,
          "GSK2126458"    ,
          "KIN001-236"     ,
          "KIN001-244"    ,
          "KIN001-055"   ,
          "KIN001-260"      ,
          "KIN001-266"    ,
          "Masitinib"      ,
          "MP470"       ,
          "MPS-1-IN-1"     ,
          "BHG712"       ,
          "OSI-930"      ,
          "OSI-027"    ,
          "CX-5461"      ,
          "PHA-793887"      ,
          "PI-103"         ,
          "PIK-93"        ,
          "SB52334"      ,
          "TPCA-1"        ,
          "TG101348"       ,
          "Foretinib"     ,
          "Y-39983"        ,
          "YM201636"       ,
          "Tivozanib"      ,
          "GSK690693"    ,
          "SNX-2112"      ,
          "QL-XI-92"      ,
          "XMD13-2"        ,
          "QL-X-138"       ,
          "XMD15-27"      ,
          "T0901317"      ,
          "EX-527"        ,
          "THZ-2-49"     ,
          "KIN001-270"    ,
          "THZ-2-102-1"    ,
          "AICAR"      ,
          "Camptothecin"  ,
          "Vinblastine"    ,
          "Cisplatin"     ,
          "Cytarabine"    ,
          "Docetaxel"      ,
          "Methotrexate"      ,
          "ATRA"        ,
          "Gefitinib"    ,
          "Navitoclax"    ,
          "Vorinostat"     ,
          "Nilotinib"      ,
          "RDEA119"      ,
          "CI-1040"     ,
          "Temsirolimus"    ,
          "Olaparib"     ,
          "Veliparib"     ,
          "Bosutinib"      ,
          "Lenalidomide"      ,
          "Axitinib"   ,
          "AZD7762"      ,
          "GW 441756"     ,
          "CEP-701"       ,
          "SB 216763"     ,
          "17-AAG"      ,
          "VX-702"      ,
          "AMG-706"     ,
          "KU-55933"     ,
          "Elesclomol"    ,
          "Afatinib"       ,
          "GDC0449"      ,
          "PLX4720"       ,
          "BX-795"          ,
          "NU-7441"      ,
          "SL 0101-1"     ,
          "BIRB 0796"       ,
          "JNK Inhibitor VIII"      ,
          "681640"       ,
          "Nutlin-3a (-)"    ,
          "PD-173074"   ,
          "ZM-447439"     ,
          "RO-3306"        ,
          "MK-2206"      ,
          "PD-0332991"    ,
          "BEZ235"          ,
          "GDC0941"     ,
          "AZD8055"     ,
          "PD-0325901"       ,
          "SB590885"      ,
          "selumetinib"    ,
          "CCT007093"       ,
          "EHT 1864"     ,
          "Cetuximab"   ,
          "PF-4708671"      ,
          "JNJ-26854165"      ,
          "HG-5-113-01"    ,
          "HG-5-88-01"    ,
          "TW 37"        ,
          "XMD11-85h"   ,
          "ZG-10"           ,
          "XMD8-92"      ,
          "QL-VIII-58"    ,
          "CCT018159"    ,
          "AG-014699"     ,
          "SB 505124"  ,
          "Tamoxifen"       ,
          "QL-XII-61"      ,
          "PFI-1"        ,
          "IOX2"       ,
          "YK 4-279"       ,
          "(5Z)-7-Oxozeaenol" ,
          "piperlongumine"   ,
          "FK866"      ,
          "Talazoparib"   ,
          "rTRAIL"    ,
          "UNC1215"        ,
          "SGC0946"      ,
          "XAV939"           ,
          "Trametinib"      ,
          "Dabrafenib"     ,
          "Temozolomide" ,
          "Bleomycin (50 uM)" ,
          "SN-38"      ,
          "MLN4924"
        )   ,
        selected="Erlotinib",
        multiple = F
      ),
      bsTooltip("drugs", "Select the drug to calculate the IC50","left"),
      
      selectizeInput(
        "drugtissueType",
        label = "Tissue type",
        choices = c("all", "allSolidTumors", "blood", "breast", "CNS", "GI tract" ,"lung", "skin", "upper aerodigestive"),
        selected="all",
        multiple = F
      ),
      bsTooltip("drugtissueType", "Specify if you would like to traing the models on only a subset of the CGP cell lines (based on the tissue type from which the cell lines originated). This be one any of 'all' (for everything, default option), 'allSolidTumors'(everything except for blood), 'blood', 'breast', 'CNS', 'GI tract' ,'lung', 'skin', 'upper aerodigestive'","left"),
      
      selectizeInput(
        "batchCorrect",
        label = "Batch correct",
        choices = c("eb","qn","none"),
        selected="eb",
        multiple = F
      ),
      
      bsTooltip("batchCorrect", "How should training and test data matrices be homogenized. Choices are 'eb' (default) for ComBat, 'qn' for quantiles normalization or 'none' for no homogenization.","left"),
      
      
      selectizeInput(
        "drugmethod",
        label = "Correlation method",
        choices = c("pearson", "spearman"),
        multiple = F,
        selected="spearman"
      ),
      
      box(title = "Size control",width = NULL,
          solidHeader = TRUE, collapsible = TRUE, collapsed = TRUE,
          sliderInput("drugwidth", "Plot Width (%)", min = 0, max = 100, value = 50),
          sliderInput("drugheight", "Plot Height (px)", min = 0, max = 1000, value = 430)
      ),
      actionButton("drugbt",
                   "Submit",
                   style = "background-color: #000080;
                                            color: #FFFFFF;
                                            margin-left: auto;
                                            margin-right: auto;
                                            width: 100%",
                   icon = icon("picture-o"))
    )
    )
  ),
  fluidRow(
    div(style="display:inline-block;vertical-align:middle;margin-left:15px; float: left;",
        actionButton(inputId = 'page_before_drug',label = '',icon = icon('arrow-left'),
                     style="color: #fff; background-color: #428bca; border-color: #2e6da4;"),
        HTML('<i>Correlation with hallmark signature</i>')
    ),
    div(style="display:inline-block;vertical-align:middle;margin-right:15px; float: right;",
        HTML('<i>Biological annotation</i>'),
        actionButton(inputId = 'page_after_drug',label = '',icon = icon('arrow-right'),
                     style="color: #fff; background-color: #428bca; border-color: #2e6da4;")
    )
  )
)